#!/bin/bash

# swap left ctrl and capslock, set keymap
setxkbmap -option 'ctrl:nocaps' 'pl(legacy)'

# turn off the screen after 10 minutes of inactivity
# xset dpms 600

# touchpad configuration 
synclient HorizTwoFingerScroll=1
synclient VertTwoFingerScroll=1
synclient EmulateTwoFingerMinZ=40
synclient EmulateTwoFingerMinW=8
synclient TapButton1=1
synclient TapButton3=2
synclient TapButton2=3
